import type { ItineraryOption } from '../types'
import { analyzeItinerary, formatCurrency } from './itineraryStats'

export function buildShareUrl(optionId: string, day?: number | null): string {
  const url = new URL(window.location.href)
  url.searchParams.set('view', 'detail')
  url.searchParams.set('id', optionId)
  if (day != null) {
    url.searchParams.set('day', String(day))
  } else {
    url.searchParams.delete('day')
  }
  return url.toString()
}

export function readUrlState(): {
  view: 'compare' | 'detail'
  id: string | null
  day: number | null
} {
  const params = new URLSearchParams(window.location.search)
  const viewParam = params.get('view')
  const view = viewParam === 'detail' ? 'detail' : 'compare'
  const id = params.get('id')
  const dayRaw = params.get('day')
  const day = dayRaw ? Number(dayRaw) : null
  return { view, id, day: Number.isFinite(day) ? day : null }
}

export function printItinerary(option: ItineraryOption): void {
  const analysis = analyzeItinerary(option)
  const route = analysis.route

  const gamesHtml = option.days
    .filter((d) => d.game && !d.game.optional)
    .map(
      (d) => `
      <tr>
        <td>Day ${d.day} · ${d.weekday} ${d.date}</td>
        <td>${d.location}</td>
        <td>${d.game!.marquee ? '⭐ ' : ''}${d.game!.matchup}${d.game!.timeLocal ? ` · ${d.game!.timeLocal}` : ''}</td>
        <td>${d.game!.interestScore.toFixed(2)}</td>
      </tr>`,
    )
    .join('')

  const legsHtml = route.legs
    .map(
      (leg) => `
      <tr>
        <td>Day ${leg.day}</td>
        <td>${leg.from} → ${leg.to}</td>
        <td>${leg.mode ?? '—'}</td>
        <td>${leg.distanceMiles != null ? `${Math.round(leg.distanceMiles)} mi` : '—'}</td>
      </tr>`,
    )
    .join('')

  const citiesHtml = analysis.daysPerCity
    .map((c) => `<li>${c.city}: ${c.days} days</li>`)
    .join('')

  const teamsHtml = analysis.gamesPerTeam
    .map((t) => `<li>${t.tricode} (${t.name}): ${t.count} game${t.count === 1 ? '' : 's'}</li>`)
    .join('')

  const b = analysis.budget
  const flightNote = b.openJaw
    ? `POA → ${b.arrivalCity}, return ${b.departureCity} (open-jaw) × ${b.travelers}`
    : `POA ↔ ${b.arrivalCity} round trip × ${b.travelers}`
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${option.name} — NBA Travels</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; color: #111; }
    h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
    h2 { font-size: 1rem; margin-top: 1.5rem; border-bottom: 1px solid #ccc; padding-bottom: 0.25rem; }
    p.meta { color: #555; font-size: 0.9rem; }
    table { width: 100%; border-collapse: collapse; font-size: 0.85rem; margin-top: 0.5rem; }
    th, td { border: 1px solid #ddd; padding: 0.4rem 0.5rem; text-align: left; }
    th { background: #f5f5f5; }
    ul { margin: 0.5rem 0; padding-left: 1.25rem; }
    .budget { display: grid; grid-template-columns: repeat(2, 1fr); gap: 0.5rem; }
    .budget div { background: #f9f9f9; padding: 0.5rem; border-radius: 4px; }
    @media print { body { margin: 1rem; } }
  </style>
</head>
<body>
  <h1>${option.name}</h1>
  <p class="meta">${option.recommendedFor}</p>
  <p class="meta">${option.startDate} → ${option.endDate} · ${option.gameCount} games · score ${option.totalInterestScore.toFixed(2)}</p>

  <h2>Budget estimate (${b.travelers} travelers)</h2>
  <div class="budget">
    <div>POA flights: ${flightNote} — ${formatCurrency(b.internationalFlights)}</div>
    <div>US domestic: ${formatCurrency(b.domesticTravel)}</div>
    <div>Hotels (1 room): ${formatCurrency(b.hotels)}</div>
    <div>Tickets × ${b.travelers}: ${formatCurrency(b.tickets)}</div>
    <div>Food × ${b.travelers}: ${formatCurrency(b.food)}</div>
    <div><strong>Total: ${formatCurrency(b.total)}</strong></div>
  </div>

  <h2>Days per city</h2>
  <ul>${citiesHtml}</ul>

  <h2>Games per team</h2>
  <ul>${teamsHtml}</ul>

  <h2>Games</h2>
  <table>
    <thead><tr><th>When</th><th>City</th><th>Matchup</th><th>Score</th></tr></thead>
    <tbody>${gamesHtml}</tbody>
  </table>

  <h2>Travel legs</h2>
  <table>
    <thead><tr><th>Day</th><th>Route</th><th>Mode</th><th>Distance</th></tr></thead>
    <tbody>${legsHtml}</tbody>
  </table>

  <p class="meta" style="margin-top:2rem">Generated by NBA Travels · estimates are approximate</p>
</body>
</html>`

  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.focus()
  win.print()
}
